// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package handler

import (
	"Ustasjs/yp-url-shortener/internal/audit"
	"Ustasjs/yp-url-shortener/internal/model"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockShortener creates a new instance of MockShortener. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockShortener(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockShortener {
	mock := &MockShortener{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockShortener is an autogenerated mock type for the Shortener type
type MockShortener struct {
	mock.Mock
}

type MockShortener_Expecter struct {
	mock *mock.Mock
}

func (_m *MockShortener) EXPECT() *MockShortener_Expecter {
	return &MockShortener_Expecter{mock: &_m.Mock}
}

// CreateShortURL provides a mock function for the type MockShortener
func (_mock *MockShortener) CreateShortURL(ctx context.Context, originalURL string, userID string) (string, error) {
	ret := _mock.Called(ctx, originalURL, userID)

	if len(ret) == 0 {
		panic("no return value specified for CreateShortURL")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return returnFunc(ctx, originalURL, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = returnFunc(ctx, originalURL, userID)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, originalURL, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockShortener_CreateShortURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateShortURL'
type MockShortener_CreateShortURL_Call struct {
	*mock.Call
}

// CreateShortURL is a helper method to define mock.On call
//   - ctx context.Context
//   - originalURL string
//   - userID string
func (_e *MockShortener_Expecter) CreateShortURL(ctx any, originalURL any, userID any) *MockShortener_CreateShortURL_Call {
	return &MockShortener_CreateShortURL_Call{Call: _e.mock.On("CreateShortURL", ctx, originalURL, userID)}
}

func (_c *MockShortener_CreateShortURL_Call) Run(run func(ctx context.Context, originalURL string, userID string)) *MockShortener_CreateShortURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockShortener_CreateShortURL_Call) Return(s string, err error) *MockShortener_CreateShortURL_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockShortener_CreateShortURL_Call) RunAndReturn(run func(ctx context.Context, originalURL string, userID string) (string, error)) *MockShortener_CreateShortURL_Call {
	_c.Call.Return(run)
	return _c
}

// CreateShortURLsBatch provides a mock function for the type MockShortener
func (_mock *MockShortener) CreateShortURLsBatch(ctx context.Context, items []model.BatchShortURLRequestItem, userID string) ([]model.BatchShortURLResponseItem, error) {
	ret := _mock.Called(ctx, items, userID)

	if len(ret) == 0 {
		panic("no return value specified for CreateShortURLsBatch")
	}

	var r0 []model.BatchShortURLResponseItem
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []model.BatchShortURLRequestItem, string) ([]model.BatchShortURLResponseItem, error)); ok {
		return returnFunc(ctx, items, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []model.BatchShortURLRequestItem, string) []model.BatchShortURLResponseItem); ok {
		r0 = returnFunc(ctx, items, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.BatchShortURLResponseItem)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []model.BatchShortURLRequestItem, string) error); ok {
		r1 = returnFunc(ctx, items, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockShortener_CreateShortURLsBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateShortURLsBatch'
type MockShortener_CreateShortURLsBatch_Call struct {
	*mock.Call
}

// CreateShortURLsBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - items []model.BatchShortURLRequestItem
//   - userID string
func (_e *MockShortener_Expecter) CreateShortURLsBatch(ctx any, items any, userID any) *MockShortener_CreateShortURLsBatch_Call {
	return &MockShortener_CreateShortURLsBatch_Call{Call: _e.mock.On("CreateShortURLsBatch", ctx, items, userID)}
}

func (_c *MockShortener_CreateShortURLsBatch_Call) Run(run func(ctx context.Context, items []model.BatchShortURLRequestItem, userID string)) *MockShortener_CreateShortURLsBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []model.BatchShortURLRequestItem
		if args[1] != nil {
			arg1 = args[1].([]model.BatchShortURLRequestItem)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockShortener_CreateShortURLsBatch_Call) Return(batchShortURLResponseItems []model.BatchShortURLResponseItem, err error) *MockShortener_CreateShortURLsBatch_Call {
	_c.Call.Return(batchShortURLResponseItems, err)
	return _c
}

func (_c *MockShortener_CreateShortURLsBatch_Call) RunAndReturn(run func(ctx context.Context, items []model.BatchShortURLRequestItem, userID string) ([]model.BatchShortURLResponseItem, error)) *MockShortener_CreateShortURLsBatch_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteURLsAsync provides a mock function for the type MockShortener
func (_mock *MockShortener) DeleteURLsAsync(userID string, shortIDs []string) error {
	ret := _mock.Called(userID, shortIDs)

	if len(ret) == 0 {
		panic("no return value specified for DeleteURLsAsync")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, []string) error); ok {
		r0 = returnFunc(userID, shortIDs)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockShortener_DeleteURLsAsync_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteURLsAsync'
type MockShortener_DeleteURLsAsync_Call struct {
	*mock.Call
}

// DeleteURLsAsync is a helper method to define mock.On call
//   - userID string
//   - shortIDs []string
func (_e *MockShortener_Expecter) DeleteURLsAsync(userID any, shortIDs any) *MockShortener_DeleteURLsAsync_Call {
	return &MockShortener_DeleteURLsAsync_Call{Call: _e.mock.On("DeleteURLsAsync", userID, shortIDs)}
}

func (_c *MockShortener_DeleteURLsAsync_Call) Run(run func(userID string, shortIDs []string)) *MockShortener_DeleteURLsAsync_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockShortener_DeleteURLsAsync_Call) Return(err error) *MockShortener_DeleteURLsAsync_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockShortener_DeleteURLsAsync_Call) RunAndReturn(run func(userID string, shortIDs []string) error) *MockShortener_DeleteURLsAsync_Call {
	_c.Call.Return(run)
	return _c
}

// GetOriginalURL provides a mock function for the type MockShortener
func (_mock *MockShortener) GetOriginalURL(ctx context.Context, id string) (string, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetOriginalURL")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockShortener_GetOriginalURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOriginalURL'
type MockShortener_GetOriginalURL_Call struct {
	*mock.Call
}

// GetOriginalURL is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockShortener_Expecter) GetOriginalURL(ctx any, id any) *MockShortener_GetOriginalURL_Call {
	return &MockShortener_GetOriginalURL_Call{Call: _e.mock.On("GetOriginalURL", ctx, id)}
}

func (_c *MockShortener_GetOriginalURL_Call) Run(run func(ctx context.Context, id string)) *MockShortener_GetOriginalURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockShortener_GetOriginalURL_Call) Return(s string, err error) *MockShortener_GetOriginalURL_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockShortener_GetOriginalURL_Call) RunAndReturn(run func(ctx context.Context, id string) (string, error)) *MockShortener_GetOriginalURL_Call {
	_c.Call.Return(run)
	return _c
}

// GetStats provides a mock function for the type MockShortener
func (_mock *MockShortener) GetStats(ctx context.Context) (model.StatsResponse, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetStats")
	}

	var r0 model.StatsResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (model.StatsResponse, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) model.StatsResponse); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(model.StatsResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockShortener_GetStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStats'
type MockShortener_GetStats_Call struct {
	*mock.Call
}

// GetStats is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockShortener_Expecter) GetStats(ctx any) *MockShortener_GetStats_Call {
	return &MockShortener_GetStats_Call{Call: _e.mock.On("GetStats", ctx)}
}

func (_c *MockShortener_GetStats_Call) Run(run func(ctx context.Context)) *MockShortener_GetStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockShortener_GetStats_Call) Return(statsResponse model.StatsResponse, err error) *MockShortener_GetStats_Call {
	_c.Call.Return(statsResponse, err)
	return _c
}

func (_c *MockShortener_GetStats_Call) RunAndReturn(run func(ctx context.Context) (model.StatsResponse, error)) *MockShortener_GetStats_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserURLs provides a mock function for the type MockShortener
func (_mock *MockShortener) GetUserURLs(ctx context.Context, userID string) ([]model.UserURLItem, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserURLs")
	}

	var r0 []model.UserURLItem
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]model.UserURLItem, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []model.UserURLItem); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.UserURLItem)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockShortener_GetUserURLs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserURLs'
type MockShortener_GetUserURLs_Call struct {
	*mock.Call
}

// GetUserURLs is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockShortener_Expecter) GetUserURLs(ctx any, userID any) *MockShortener_GetUserURLs_Call {
	return &MockShortener_GetUserURLs_Call{Call: _e.mock.On("GetUserURLs", ctx, userID)}
}

func (_c *MockShortener_GetUserURLs_Call) Run(run func(ctx context.Context, userID string)) *MockShortener_GetUserURLs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockShortener_GetUserURLs_Call) Return(userURLItems []model.UserURLItem, err error) *MockShortener_GetUserURLs_Call {
	_c.Call.Return(userURLItems, err)
	return _c
}

func (_c *MockShortener_GetUserURLs_Call) RunAndReturn(run func(ctx context.Context, userID string) ([]model.UserURLItem, error)) *MockShortener_GetUserURLs_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPinger creates a new instance of MockPinger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPinger(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPinger {
	mock := &MockPinger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPinger is an autogenerated mock type for the Pinger type
type MockPinger struct {
	mock.Mock
}

type MockPinger_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPinger) EXPECT() *MockPinger_Expecter {
	return &MockPinger_Expecter{mock: &_m.Mock}
}

// PingContext provides a mock function for the type MockPinger
func (_mock *MockPinger) PingContext(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for PingContext")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPinger_PingContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PingContext'
type MockPinger_PingContext_Call struct {
	*mock.Call
}

// PingContext is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockPinger_Expecter) PingContext(ctx any) *MockPinger_PingContext_Call {
	return &MockPinger_PingContext_Call{Call: _e.mock.On("PingContext", ctx)}
}

func (_c *MockPinger_PingContext_Call) Run(run func(ctx context.Context)) *MockPinger_PingContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPinger_PingContext_Call) Return(err error) *MockPinger_PingContext_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPinger_PingContext_Call) RunAndReturn(run func(ctx context.Context) error) *MockPinger_PingContext_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuditPublisher creates a new instance of MockAuditPublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuditPublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuditPublisher {
	mock := &MockAuditPublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuditPublisher is an autogenerated mock type for the AuditPublisher type
type MockAuditPublisher struct {
	mock.Mock
}

type MockAuditPublisher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuditPublisher) EXPECT() *MockAuditPublisher_Expecter {
	return &MockAuditPublisher_Expecter{mock: &_m.Mock}
}

// Publish provides a mock function for the type MockAuditPublisher
func (_mock *MockAuditPublisher) Publish(event audit.Event) {
	_mock.Called(event)
	return
}

// MockAuditPublisher_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type MockAuditPublisher_Publish_Call struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - event audit.Event
func (_e *MockAuditPublisher_Expecter) Publish(event any) *MockAuditPublisher_Publish_Call {
	return &MockAuditPublisher_Publish_Call{Call: _e.mock.On("Publish", event)}
}

func (_c *MockAuditPublisher_Publish_Call) Run(run func(event audit.Event)) *MockAuditPublisher_Publish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 audit.Event
		if args[0] != nil {
			arg0 = args[0].(audit.Event)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAuditPublisher_Publish_Call) Return() *MockAuditPublisher_Publish_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAuditPublisher_Publish_Call) RunAndReturn(run func(event audit.Event)) *MockAuditPublisher_Publish_Call {
	_c.Run(run)
	return _c
}
